name: "Deploy to Baseplate"
description: "Deploy microfrontends to Baseplate"
inputs:
  baseplate-token:
    description: "BASEPLATE_TOKEN is a service account token with deploy access"
    required: true
  microfrontend-name:
    description: The name of the Baseplate microfrontend to be deployed
  environment-name:
    description: The name of the Baseplate environment to deploy to
  upload-dir:
    description: The directory containing all files for this microfrontend's deployment
  entry-file:
    description: The entry file that will be put into the import map. This is a relative file path within the upload dir.
  auto-version:
    description: Whether baseplate should upload deployed files under an auto-versioned virtual folder, to avoid collisions with previous deployments.
runs:
  using: "node20"
  main: "dist/index.mjs"
